### ISSUE TITLE
question about workflow

### ISSUE THREAD

**Issue by jaredleechn** [Ognian/reactIntlJson-loader#1]
good job for intl solution of react, but there's still a question
- how to combine the json file(especially when dev the file is in memory) with your source code
  
  maybe import the json file into your entry file? But the json file is unavailable before all things compiled

**Comment by Ognian** [comment]
as long as dev server is running you can:
- use the browser an check http://localhost:devServerPort/reactIntlMessages.json
- or, like I do, add a script to package.json like `"trans:refreshJsonDEV": "curl localhost:3100/reactIntlMessages.json >./dist/reactIntlMessages.json"`

The translation of `./dist/reactIntlMessages.json` file to i.e. `./src/reactIntlMessages-de.json` is done (for now) manually via  CAT Tools (I'm using the cloud based memsource.com).

I have also started https://github.com/Ognian/reactIntlJson-translator but it will take some time to finish since I'm very busy now...

**Comment by jaredleechn** [comment]
ok

I think the keyword is `manually`, very thanks
